server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    co.insecurity: DEBUG
  file:
    name: ./demo.log

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: CHANGEME
            clientSecret: CHANEGME
          okta:
            client-id: CHANEGME
            client-secret: CHANEGME
        provider:
          okta:
            issuer-uri: CHANGEME

      resourceserver:
        jwt:
          issuer-uri: CHANGEME
          jws-algorithm: RS256

my:
  oauth2:
    resource-server:
      allowed-audience-values:
        - api://default

management:
  server:
    port: -1
